rm -R -f platforms/ios/www/node_modules
rm -R -f platforms/ios/www/test
rm -R -f platforms/ios/www/polyfills
rm -R -f platforms/ios/www/config.rb
rm -R -f platforms/ios/www/Gruntfile.js
rm -R -f platforms/ios/www/background.js
rm -R -f platforms/ios/www/.sass-cache
rm -R -f platforms/ios/www/.git
rm -R -f platforms/ios/www/.gitignore

rm -R -f platforms/android/assets/www/node_modules
rm -R -f platforms/android/assets/www/test
rm -R -f platforms/android/assets/www/polyfills
rm -R -f platforms/android/assets/www/config.rb
rm -R -f platforms/android/assets/www/Gruntfile.js
rm -R -f platforms/android/assets/www/background.js
rm -R -f platforms/android/assets/www/.sass-cache
rm -R -f platforms/android/assets/www/.git
rm -R -f platforms/android/assets/www/.gitignore